### ISSUE TITLE
Update for template pack despite new install

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/templates#28] opened 2021-05-01 13:09 UTC
After installing the current latest templates (`dotnet new -i WebSharper.Templates`), I tried to create a new `websharper-web` project and got:

```
C:\tests>dotnet new websharper-web -n MyTestApp -lang f#
The template "WebSharper 4 Client-Server Application" was created successfully.

An update for template pack WebSharper.Templates::4.7.1.409 is available.
    install command: dotnet new -i WebSharper.Templates::4.7.0.395 
```

Note that the versions don't make sense.

**Comment by mrtank** [comment] 2021-09-10 08:22
```
An update for template pack WebSharper.Templates::5.0.0.102-preview1 is available.
    install command: dotnet new -i WebSharper.Templates::5.0.0.102-preview1
```
It can even suggest to install the same version

**Comment by Jand42** [comment] 2022-03-08 09:16
I can't reproduce this with either WS 5 packages (when only nuget.org source is used) or WS6 when (GH packages source is used). Either updated package metadata or nuget.orgs updates have fixed it, closing for now.

**Closed by Jand42** 2022-03-08 09:16 UTC
Labels: bug
